config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get "/correo" => "application#email"
  resources :users
  resources :plants
  get "/auth/:provider/callback" => "users#connect"
  post "/login" => "users#login", as: "login"
  get "/signout" => "users#signout", as: "signout"
  get "/map" => "application#showmap" , as: "map"

  get "/plants" => "users#showlist", as: "list"

  get "/:short" => "application#language"

  get "verifica/:uuid", to: "users#email_verification", as: "confirmemail"

  get "/users/:id/favorites" => "users#favoritos", as: "favorites"
  get "/users/:id/history" => "users#historial", as: "history"

  patch "/users/:id/inactive" => "users#inactive", as: "inactive"

  patch "/plants/:id/addfavs" => "plants#addfavs", as: "addfavs"

  patch "/users/:id/changerole" => "users#changerole", as: "changerole"

  patch "/users/:id/activacionadmin" => "users#activacionadmin", as: "activacionadmin"
  
  get "forgot/f", to: "users#forgot_pass", as:"forgot_view"
  post "/forgot" => "users#forgot_check", as: "forgot_check"
  
  get "forgot/:uuid" => "users#forgot_change", as: "forgot_change"
  patch "/forgot/:uuid/success" => "users#forgot_success", as: "forgot_success"

end

app/models/user.rb
class User < ActiveRecord::Base

	before_create :set_password, unless: :provider_uid?
	
	#validates :name, :gender, :image, presence: true
	validates :username, presence: true, on: :create, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }, length: { minimum: 4 }
	validates :name, :gender, :role, :estado, presence: true, on: :create
	validates :email, presence: true, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
	#validates :password, presence: true, length: { minimum: 6 }, unless: :provider_uid?, on: :forgot_success
	validates :password, presence: true, length: { minimum: 6 }, unless: :provider_uid?

	belongs_to :plant

	# Este método te asignará la encriptación solo si el campo es valido
	# Es decir si el campo tiene mínimo 6 caracteres.
	def set_password
      if self.valid?
      	self.password = Digest::SHA1.hexdigest(self.password)
      end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  $vista = 0

  def index

    @user = User.find(session[:user]) if session[:user]

    if  @user.role < 2
      $vista = 1

      @users = User.all
      #render "index"
      respond_to do |format|
        format.html
        format.json {render json: @users}
      end

    end

  end

  # Vista del perfil de usuario
  def show

    @us = User.find(session[:user])

    if @us.role < 2
      $vista = 0
      @user = User.find(params[:id])
      puts "EL ID ES=" + params[:id]
      puts "LA SESION ES=" + session[:user].to_s

      respond_to do |format|
        format.html
        format.json {render json: @user}
      end
    else
      if session[:user].to_s == params[:id]
        
        $vista = 0
        @user = User.find(params[:id])
        puts "EL ID ES=" + params[:id]
        puts "LA SESION ES=" + session[:user].to_s

        respond_to do |format|
          format.html
          format.json {render json: @user}
        end

      end

    end

  end


  # Vista para editar.
  def edit

    @user = User.find(params[:id]) if session[:user]
    respond_to do |format|
      format.html
      format.json {render json: @user}
    end

  end

  def update
    @user = User.find(params[:id])

    if !@user.provider_uid
      @user.password = Digest::SHA1.hexdigest(user_params[:password])
    end


    if params[:user][:image] && !params[:user][:image].is_a?(String)
      if @user.image && Dir.glob("public#{@user.id}_#{@user.name}").count > 0
        File.delete("public#{@user.id}_#{@user.name}")
      end
      #@user.image = "/uploads/users/#{Random.new_seed.to_s}.#{params[:user][:image].original_filename.split(".").last}"
      @user.image = "/uploads/users/#{@user.id}_#{@user.name}.#{params[:user][:image].original_filename.split(".").last}"
      File.open('public' + @user.image, "wb") do |f|
        f.write(params[:user][:image].read)
      end
    end

    params[:user][:password] = @user.password
    params[:user][:image] = @user.image

    if @user.update(user_params)
        
        if $vista == 1
          redirect_to users_path
        else
          redirect_to @user
        end

    else
      render "perfil"
    end

  end

  def changerole
    @user = User.find(params[:id])
    @user.role = user_params[:role]

    if @user.save
      redirect_to users_path
    end

  end

  def favoritos 
    @user = User.find(session[:user]) if session[:user]
    @plants = Plant.all
    @plants_user = []

    @plants.each do |plant|
      if plant.favs.include?(@user.id) 
       @plants_user.push( plant )
      end
    end

      respond_to do |format|
        format.html
        format.json {render json: @plants_user}
      end

  end

  def historial
    render "history"
  end

  # Método para guardar datos del usuario nuevo.
  def create
    #params.except!( :password_c )
    #puts "CLAVESINHA: "+params[:password_c].to_s

    @user = User.new(user_params)
    @user.uuid = Digest::SHA1.hexdigest(@user.id.to_s)
    @user.estado=1
    @user.role=2

   # pass = params[:user][:password]
   # puts "CLAVESINHA:" + pass
   # puts "CLAVESINHA2:" + params[:user][:password]

    if params[:user][:image] && !params[:user][:image].is_a?(String)
      if @user.image && Dir.glob("public#{@user.id}_#{@user.name}").count > 0
        File.delete("public#{@user.id}_#{@user.name}")
      end
      #@user.image = "/uploads/users/#{Random.new_seed.to_s}.#{params[:user][:image].original_filename.split(".").last}"
      @user.image = "/uploads/users/#{@user.id}_#{@user.name}.#{params[:user][:image].original_filename.split(".").last}"
      File.open('public' + @user.image, "wb") do |f|
        f.write(params[:user][:image].read)
      end
    end
    
    if @user.save

      if !@user.provider_uid
      #session[:user] = @user.id
      #@url = "http://localhost:3000/verifica/" + @user.id.to_s
      @url = request.protocol + request.host_with_port + "/verifica/" + @user.uuid
      puts "URL ACT:" + @url
      ClienteMailer.email_verification(@user.name, @user.email, @url).deliver_now

      
        #redirect_to user_path(@user)
      flash[:notice] = 'Se ha enviado un correo a tu cuenta, por favor confirma tu correo'
      redirect_to root_path
    else
      session[:user] = @user.id
      redirect_to user_path(@user)
    end

    elsif params[:user][:provider_uid]
      #@user.errors = nil
      render "tw_new"
    else
      render "new"
    end

  end

  def new
  # Esto debería ser el formulario de creación de usuarios.
  #render json: params[:data], content_type: "application/json"    
  end


    # Método para guardar datos de facebook, twitter.
  def connect
    if env["omniauth.auth"]
      @user = User.where(provider_uid: env["omniauth.auth"]["uid"]).first
      unless @user
        @user = User.new
        @user.name = env["omniauth.auth"]["extra"]["raw_info"]["name"]
        @user.email = env["omniauth.auth"]["extra"]["raw_info"]["email"]
        @user.image = env["omniauth.auth"]["info"]["image"]
        @user.gender = env["omniauth.auth"]["extra"]["raw_info"]["gender"]
        @user.verified = env["omniauth.auth"]["extra"]["raw_info"]["verified"]
        @user.provider_uid = env["omniauth.auth"]["uid"]
        @user.username = env["omniauth.auth"]["uid"]
        @user.role = 2
        @user.estado = 1

        @user.uuid = Digest::SHA1.hexdigest(@user.id.to_s)

        #puts env["omniauth.auth"]["extra"]["raw_info"]["name"].to_s
        #puts env["omniauth.auth"]["extra"]["raw_info"]["email"].to_s
        #puts env["omniauth.auth"]["extra"]["raw_info"]["gender"].to_s
        #puts env["omniauth.auth"]["extra"]["raw_info"]["verified"].to_s
        #puts env["omniauth.auth"]["uid"].to_s
=begin        
        if env["omniauth.auth"]["extra"]["raw_info"]["email"]
          @user.username = env["omniauth.auth"]["uid"]
        else
          @user.username = env["omniauth.auth"]["uid"]["nickname"]
        end
=end
        if @user.save
            session[:user] = @user.id
            redirect_to user_path(@user)
            #render json: @user, content_type: "application/json"
            #render json: env["omniauth.auth"], content_type: "application/json"
        else
          #if @user.email
            
            #render json: env["omniauth.auth"], content_type: "application/json"
            #flash[:notice] = 'Ya existes'
            #render "/index"

          #else
            
            #@user.username = env["omniauth.auth"]["info"]["nickname"]
            if env["omniauth.auth"]["extra"]["raw_info"]["email"]
              flash[:notice] = @user.username
            end

            @user.errors.clear
            render "tw_new"
            #render json: env["omniauth.auth"], content_type: "application/json"
          #end
        end

      else
        if @user.estado != 0
          session[:user] = @user.id
          flash[:notice] = 'Logueado satisfactoriamente'
          redirect_to user_path(@user)
        else
          flash[:notice] = 'Inactivo viejo'
          redirect_to root_path
        end
      end
    elsif params[:error]
      render plain: "#{params[:error]} #{params[:error_reason]}", content_type: "application/plain"
    else
      render plain: "No se pudo conectar con #{params[:provider]}", content_type: "application/plain"
    end
  end

  def login
    user = User.where(username: user_params[:username]).first

    input_pass = Digest::SHA1.hexdigest(user_params[:password])
    #input_pass = user_params[:password]

    #puts "PP:" + user_params[:password]
    #puts "passesC: "+ user.password + "_" + input_pass

    if user
      user.forgot = nil

      if user.save

        if user.verified

          if user.estado == 1

            if !user.provider_uid

                if user.password == input_pass
                  session[:user] = user.id.to_s
                  flash[:notice] = 'Logueado satisfactoriamente'
                  redirect_to user_path(user)
                else
                  #flash[:notice] = "Correo o contraseña incorrectos"
                  flash[:notice] = t :wrongpass
                  render "/index"
                end
            else
              flash[:notice] = t :wrongsocial
              render "/index"
            end

          else

              if user.password == input_pass
                user.image = nil
                user.estado = 1
                session[:user] = user.id.to_s

                plants = Plant.all

                if plants
                  for i in 0...plants.length
                    if plants[i].favs.include?(user.id)
                      plants[i].favs.delete(user.id)
                    end
                    if plants[i].save
                      puts "BORRADO FAVORITO DE " + plants[i].name.to_s
                    end
                  end
                end
                
                if user.save
                  flash[:notice] = "Bienvenido de nuevo"
                 redirect_to user_path(user)
                end

              else
                flash[:notice] = "Usuario o contraseña incorrectos"
                #flash[:notice] = "Nonono"
                render "/index"
              end

          end
        else
          flash[:notice] = 'Primero confirma tu correo'
          render "/index"
        end

      else
        flash[:notice] = "Usuario o contraseña incorrectos"
        #flash[:notice] = t :wrongpass
        render "/index"
      end
    else
        flash[:notice] = "Usuario o contraseña incorrectos"
        #flash[:notice] = t :wrongpass
        render "/index"
    end

  end

  def signout
    session[:user]=nil
    redirect_to "/"
  end

  def inactive
    @user = User.find(session[:user])
    @user.estado = 0

    #render "/index"
    if @user.update(user_params)
      redirect_to "/index"
      session[:user]=nil
    else
      render "perfil"
    end
  end

  def email_verification

    #user = User.find(params[:uuid])

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<link rel="stylesheet" type="text/css" href="/assets/newyedit.css">

<a id="volver" href="<%= user_path(@user) %>">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver
</a>	
	
<div class="fold_new">

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

	<h1>Perfil</h1>

		<% if @user && @user.errors.any? %>
			<div id="error_explanation">
				<h2>
					Existen <%=pluralize(@user.errors.count, "error", "errores")%> en el formulario.
				</h2>
				<ul class="list-group">
					<% @user.errors.full_messages.each do |msg| %>
						<li class="list-group-item list-group-item-danger"><%= msg %></li>
					<% end %>
				</ul>	
			</div>
		<% end %>

		<div class="input-group">
			<span class="input-group-addon" id="basic-addon1">
			<%=f.label :name, "Nombre"%></span>
			<%=f.text_field :name, :class => "form-control"  %>
		</div>

		<div class="input-group">
			<span class="input-group-addon" id="basic-addon1">
			<%=f.label :username, "Usuario"%></span>
			<%=f.text_field :username, :class => "form-control"  %>
		</div>

		<div class="input-group">
			<span class="input-group-addon" id="basic-addon1">
			<%=f.label :email, "Correo"%></span>
			<%=f.text_field :email, :class => "form-control" %>
		</div>
		
		<% if !@user.provider_uid %>
		
			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1">
				<%=f.label :password, "Contraseña"%></span>
				<%=f.password_field :password, :class => "form-control", :id => "pass" %>
			</div>

			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1">
				<%=f.label :password_c, "Confirmar"%> </span>
				<%=f.password_field :password_confirmation, :class => "form-control", :id => "pass_c" %>
			</div>

			<%= f.file_field 'image', :class => "input_image" %>
			<img src="" alt="" class="thumbnail">
				
		<% end %>

			<div class="input-group">
      			<span class="input-group-addon">
  				<%= f.radio_button(:gender, "male")%></span>
      			<%= f.label :gender_male, "Hombre", :class => "form-control" %>
      		</div>

			<div class="input-group">
  				<span class="input-group-addon">
  				<%= f.radio_button(:gender, "female")%></span>
  			<%= f.label :gender_female, "Mujer", :class => "form-control" %>
  			</div>	

	
			<%=f.submit "Guardar cambios", :class => "btn btn-warning", :id => "enviar" %>


<% end %>

	<%if !@user.provider_uid  || @role != 0 %>
		<%= form_for :user, url: inactive_path(@user), method: :patch do |f| %>
			<%= f.hidden_field "name" %>
			<%= f.hidden_field "email" %>
			<%= f.hidden_field "password" %>
			<%= f.hidden_field "gender" %>
			<%=f.submit "Desactivar mi cuenta",id: "desactivar", :class => "btn btn-danger" , data:{confirm: "¿Esta seguro?"} %>
		<% end %>
	<% end %>
<!--
			<a class="btn btn-info" href="/en">ENG</a>
			<a class="btn btn-info" href="/es">ESP</a>		
-->

</div>


<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/imagen_carga.js" ></script>
<% end %>

app/views/users/favoritos.html.erb
<link rel="stylesheet" type="text/css" href="/assets/listas.css">

<div class="superior">
	<a id="volver" href="/">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver al inicio
	</a>
</div>


<div class="superior">
	<a id="volver" href="/">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver al inicio
	</a>
</div>

<div class="container">
    <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Favoritos</h3>
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span>Filtrar</button>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Id" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Nombre" disabled></th>
                    </tr>
                </thead>
                <tbody>

                    <% @plants_user.each do |plant| %>
                		<tr>
                			<td style="width: 80px;">
                				<%= plant.id %>
                			</td>

                			<td> 
                				<%= link_to plant.name, plant_path(plant) %>
                			</td>
                		</tr>		
                	<% end %>

                </tbody>
            </table>
        </div>
    </div>
<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/listas.js" ></script>
<% end %>

app/views/users/forgot_change.html.erb
<link rel="stylesheet" type="text/css" href="/assets/forgot.css">

<div class="forgot_fold">

	<h3>Por favor escribe tu nueva contraseña</h3>

	
			<% if flash[:notice] %>
				<div class="alert alert-danger" role="alert">
					<%= flash[:notice] %>
				</div>
			<% end %>

	<% if @user && @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				Existen <%=pluralize(@user.errors.count, "error", "errores")%> en el formulario.
			</h2>
			<ul class="list-group">
				<% @user.errors.full_messages.each do |msg| %>
					<li class="list-group-item list-group-item-danger" ><%= msg %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>

	<%= form_for :user, url: forgot_success_path(@user.uuid), method: :patch do |f| %>
		<div class="input-group">

		<div class="input-group">
			<span class="input-group-addon" id="basic-addon1">
			<%=f.label :password, "Nueva contraseña"%> </span>
			<%=f.password_field :password, :class => "form-control", :id => "pass" %>
		</div>

		<div class="input-group">
			<span class="input-group-addon" id="basic-addon1">
			<%=f.label :password_c, "Confirmar"%> </span>
			<%=f.password_field :password_confirmation, :class => "form-control", :id => "pass_c" %>
		</div>

		<%=f.password_field :password, :class => "form-control" %>
		</div>

		<%=f.submit "Cambiar", :class => "btn btn-success" , :id => "enviar" %>

	<% end %>

</div>

app/views/users/history.html.erb
<div class="fold_historial">
	<div class="encabezado">
		<table>
			<tr>
				<td id="volver">
					<a href="/"><img src="/assets/back.png"></td></a>
				<td id="titulo">Historial</td>
				<td></td>
			</tr>
		</table>
	</div>
	<div class="contenido">
		<table>
			<% for i in 0..4 %>
				<tr>
					<td style="width:40px;">
						<img src="/assets/logo_1.jpg">
					</td>
					<td id="nombre">
						<a href="">Visto: Arbol <%= i+1 %></a>
						<p><%= 5-i %>/06/2015</p>
					</td>
				</tr>
			<% end %>
			<% for i in 0..7 %>
				<tr>
					<td style="width:40px;">
						<img src="/assets/fav.png">
					</td>
					<td id="nombre">
						<a href="">Favoritos: Arbol <%= i+1 %></a>
						<p><%= 8-i %>/06/2015</p>
					</td>
				</tr>
			<% end %>

		</table>
	</div>

</div>

app/views/users/index.html.erb
<link rel="stylesheet" type="text/css" href="/assets/listas.css">

<div class="superior">
	<a id="volver" href="/">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver al inicio
	</a>
</div>

<div class="container">
    <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Usuarios</h3>
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span>Filtrar</button>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Id" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Usuario" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Rol" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Estado" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Verf" disabled></th>
                        <th colspan="4">Acciones</th>
                    </tr>
                </thead>
                <tbody>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= user.id %>
						</td>

						<% if !user.provider_uid %>
							<% if @user.id == user.id %>
								<th><%= user.username %></th>
							<% else %>	
								<td><%= user.username %></td>
							<% end %>
						<% else %>
							<% if @user.id == user.id %>
								<th><%= user.name %></th>
							<% else %>	
								<td><%= user.name %></td>
							<% end %>
						<% end %>	
							
						<% if user.role.to_i == 0 %>
							<td>Super Admin</td>
						<% elsif user.role.to_i == 1 %>
							<td>Admin</td>
						<% elsif user.role.to_i == 2 %>
							<td>Usuario</td>
						<% end %>

						
						<% if user.estado == 0 %>
							<td>Inactivo</td>
						<% else %>
							<td>Activo</td>
						<% end %>

						<% if user.verified %>
							<td>Si</td>
						<% else %>
							<td>No</td>
						<% end %>

						<% if user.role.to_i != 0 %>
							<% if @user.role.to_i < user.role.to_i || @user.id == user.id %>
								<td>
									<%= link_to 'Editar' , edit_user_path(user) %>
								</td>

								<td>
									<%= link_to "Eliminar", user_path(user), method: :delete, data:{confirm: "¿Esta seguro?"} %>
								</td>
								
								<td>
									<%= form_for :user, url: changerole_path(user), method: :patch do |f| %>	


										<%= f.select 'role', options_for_select([["Admin", 1], ["User", 2]]) %>

										<%= f.submit 'Change' %>
									<% end %>

								</td>

								<% if !user.provider_uid %>
									<td>

										<% if user.estado == 1 %>
											<%= form_for :user, url: activacionadmin_path(user), method: :patch do |f| %>
												<%= f.submit 'Dar de baja' %>
											<% end %>
										<% else %>
											<%= form_for :user, url: activacionadmin_path(user), method: :patch do |f| %>	
												<%= f.submit 'Dar de alta' %>
											<% end %>
										<% end %>	

									</td>
								<% end %>

							<% else %>	
								<td></td>
								<td></td>
								<td></td>
							<% end %>
						<% else %>
							<td></td>
							<td></td>
							<td></td>	
						<% end %>
					</tr>
				<% end %>

                </tbody>
            </table>
        </div>
    </div>
<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/listas.js" ></script>
<% end %>

app/views/users/show.html.erb
<link rel="stylesheet" type="text/css" href="/assets/users.css">



<div class="fold_show_user">
	<div class="fondo_colorido">

		<div class="encabezado">
			
			<table>
				<tr>
					<td>
						<% if @user.image %>
							<img id="img_perfil" src="<%= @user.image %>" class="thumbnail">
						<% else %>
								<img id="img_perfil" src="/assets/logo_2.png" class="thumbnail">
						<% end %>
					</td>

					<td>
						<h2> <%= @user.name %> </h2>
					</td>

					<td id="mod" href="#modal_opcs" class="modal_director">
						<a id="volver">
							<span class="glyphicon glyphicon-leaf" aria-hidden="true"></span> 
						</a>
					</td>
				</tr>
			</table>

		</div>

		<div class="contenido">

			<% if flash[:notice] %>
				<div class="alert alert-warning" role="alert">
					<%= flash[:notice] %>
				</div>
			<% end %>
			
			<div class="busqueda" > 
				<a id="buscar_btn" class="btn btn-success" >Buscar plantas</a>

				<div id="err_aviso">
				</div>

				<div id="cont_refre">
					<span class="glyphicon glyphicon-repeat" aria-hidden="true"></span>
				</div>
			</div>

			<ul id="lista_a" class="list-group">
			</ul>

			<div id="map-canvas" style="height:0"></div>


		</div>
	</div>
</div>


			<!--MODAL -->
<div hidden class="modal_actor" id="modal_opcs">
	<div class="modal_content">
		<ul class="list-group">
			
			<% if @user.role != 2 %>
			<li class="list-group-item">
				<a href="/users">
				<span class="glyphicon glyphicon-list" aria-hidden="true"></span> 
				Usuarios</a>
			</li>
			<% end %>
			<li class="list-group-item">
				<a href="<%= list_path %>">
				<span class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span> 
				Arboles</a>
			</li>
			<li class="list-group-item">
				<a href="<%= edit_user_path(@user) %>">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
				<%= t :profile %></a>
			</li>
			<li class="list-group-item">
				<a href="<%= map_path %>">
				<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
				<%= t :map %></a>
			</li>
			<li class="list-group-item">
				<a href="<%= favorites_path %>">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
				<%= t :favorites %></a>
			</li>
			<!-- <li><a href="<%= history_path %>"><%= t :history %></a></li> -->
			<li class="list-group-item"><a href="/signout">
				<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
				<%= t :logout %></a>
			</li>
		</ul>
	</div>
</div>

<script type="text/javascript" src="/assets/show.js"></script>
<!--
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB8lONMbO96_r_hmWz5j7Q4sgW6wadLHew"></script>
-->

app/views/users/tw_new.html.erb
<link rel="stylesheet" type="text/css" href="/assets/newyedit.css">

<div class="fold_new">
<h1>Un pasito más</h1>
<%= form_for :user, url: users_path do |f| %>

		<% if @user && @user.errors.any? %>
			<div id="error_explanation">
				<h2>
					Existen <%=pluralize(@user.errors.count, "error", "errores")%> en el formulario.
				</h2>
				<ul class="list-group">
					<% @user.errors.full_messages.each do |msg| %>
						<li class="list-group-item list-group-item-danger" ><%= msg %></li>
					<% end %>
				</ul>	
			</div>
		<% end %>

	<%= f.hidden_field "name", :class => "mi_clase" %>
	<%= f.hidden_field "provider_uid" %>
	<%= f.hidden_field "image"  %>

	<% if flash[:notice] %>
				<div class="alert alert-warning" role="alert">
					<%= flash[:notice] %>
				</div>
	<% end %>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :username, "Usuario" %> </span>
		<%=f.text_field :username, :class => "form-control" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :email, "Correo"%> </span>
		<%=f.text_field :email, :class => "form-control" %>
	</div>

	<div class="input-group">
			<span class="input-group-addon">
				<%= f.radio_button(:gender, "male")%>
			</span>
			<%= f.label :gender_male, "Hombre", :class => "form-control" %>
		</div>

	<div class="input-group">
			<span class="input-group-addon">
				<%= f.radio_button(:gender, "female")%>
			</span>
			<%= f.label :gender_female, "Mujer", :class => "form-control" %>
	</div>	

	<img src="<%= @user.image %>" alt="" class="thumbnail">
	<%= f.submit "Crear usuario", :class => "btn btn-success" %>

<% end %>

	<a id="volver_2" href="/">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Cancelar
	</a>
	
</div>