config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get "/correo" => "application#email"
  resources :users
  resources :plants
  get "/auth/:provider/callback" => "users#connect"
  post "/login" => "users#login", as: "login"
  get "/signout" => "users#signout", as: "signout"
  get "/map" => "application#showmap" , as: "map"

  get "/plants" => "users#showlist", as: "list"

  get "/:short" => "application#language"

  get "verifica/:uuid", to: "users#email_verification", as: "confirmemail"

  get "/users/:id/favorites" => "users#favoritos", as: "favorites"
  get "/users/:id/history" => "users#historial", as: "history"

  patch "/users/:id/inactive" => "users#inactive", as: "inactive"

  patch "/plants/:id/addfavs" => "plants#addfavs", as: "addfavs"

  patch "/users/:id/changerole" => "users#changerole", as: "changerole"

  patch "/users/:id/activacionadmin" => "users#activacionadmin", as: "activacionadmin"
  
  get "forgot/f", to: "users#forgot_pass", as:"forgot_view"
  post "/forgot" => "users#forgot_check", as: "forgot_check"
  
  get "forgot/:uuid" => "users#forgot_change", as: "forgot_change"
  patch "/forgot/:uuid/success" => "users#forgot_success", as: "forgot_success"

end

app/models/plant.rb
class Plant < ActiveRecord::Base

	validates :common_name, :resume,:description,:distribution,:etnobotanic, presence: true
	validates :name, presence: true, uniqueness: true
	validates :latitude, :longitude, presence: true, uniqueness: true, :numericality => {:only_float => true}

	#Si es a muchos
	has_many :users

	#Si es a uno
	#belongs_to :user
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = Plant.all
    @user = User.find(session[:user])
    #render "index"
    respond_to do |format|
      format.html
      format.json {render json: @plants}
    end
    
  end

  def new
    if session[:user]
  	   @user = User.find(session[:user]) 
      render "new_plant"
    end
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user_id = session[:user]

    if plant_params[:images]

    if plant_params[:images].length.to_i <= 5


      for i in 0...plant_params[:images].length


        if plant_params[:images][i] && !plant_params[:images][i].is_a?(String)
          if @plant.images[i] && Dir.glob("public#{i}_#{@plant.name}").count > 0
            File.delete("public#{i}_#{@plant.name}")
          end

          pushval = "/uploads/plants/" + i.to_s + "_" + @plant.name + "." + plant_params[:images][i].original_filename.split(".").last
          #puts "RUTA: "+ pushval
          @plant.images[i] = pushval
          #puts "RUTA2: "+ @plant.images[i]

          File.open('public' + @plant.images[i], 'wb') do |f|
            f.write(plant_params[:images][i].read)
          end

        end
      end

      if @plant.save
        redirect_to @plant
      else
        render "new_plant"
      end

    else
      @plant.errors.add(:images, "Maximo 5 imgs") if plant_params[:images].length.to_i > 5
      render "new_plant"
    end
  else
      if @plant.save
        redirect_to @plant
      else
        render "new_plant"
      end
  end

  end

  def show
    @user = User.find(session[:user]) if session[:user]
    @plant = Plant.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @plant}
    end
  end

  # Vista para editar.
  def edit
    @plant = Plant.find(params[:id])
    render "edit"
  end

  def update
    @plant = Plant.find(params[:id])
    #@plant.user_id = session[:user]

    if plant_params[:images]
      
      if plant_params[:images].length.to_i <= 5

      if @plant.images.length > 0
        for i in 0...@plant.images.length
          File.delete(Rails.public_path + "uploads/plants/#{i}_#{@plant.name}.#{@plant.images[0].split(".").last}")
        end
        @plant.images = []
      end

        for i in 0...plant_params[:images].length
          if plant_params[:images][i] && !plant_params[:images][i].is_a?(String)
            if @plant.images[i] && Dir.glob("public#{i}_#{@plant.name}").count > 0
              File.delete("public#{i}_#{@plant.name}")
            end

            @plant.images.push( "/uploads/plants/#{i}_#{@plant.name}.#{plant_params[:images][i].original_filename.split(".").last}" )
            
            File.open('public' + @plant.images[i], "wb") do |f|
              f.write(plant_params[:images][i].read)
            end

          end
          params[:plant][:images][i] = @plant.images[i]
        end

        if @plant.update(plant_params)
          redirect_to @plant
        else
          render "edit"
        end

      else
        @plant.errors.add(:images, "Maximo 5 imgs") if plant_params[:images].length.to_i > 5
        render "new_plant"
      end

    else
      if @plant.images.length > 0
        for i in 0...@plant.images.length
          File.delete(Rails.public_path + "uploads/plants/#{i}_#{@plant.id}.#{@plant.images[0].split(".").last}")
        end
        @plant.images = []
      end
      
      if @plant.update(plant_params)
        redirect_to @plant
      else
        render "edit"
      end  
    end
  end

  def addfavs
    @user = User.find(session[:user]) if session[:user]
    @plant = Plant.find(params[:id])
    puts "EL ID: " + @user.id.to_s


    if !@plant.favs.include?(@user.id)

      @plant.favs.push(@user.id)
      puts "ARR: " + @plant.favs.to_s
      
      if @plant.update(plant_params)
        redirect_to @plant
      end

    else
      @plant.favs.delete(@user.id)

      if @plant.update(plant_params)
        redirect_to @plant
      end
      #redirect_to @plant
    end

  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to plants_path
  end

  private
  def plant_params
    params.require(:plant).permit(:name, :common_name, :resume,:description,:distribution,:etnobotanic, :latitude, :longitude, :user_id, :favs, images:[] )
  end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/edit.html.erb
<link rel="stylesheet" type="text/css" href="/assets/newyedit.css">


<div class="fold_new ">
	<h1>Modificar</h1>
<%= form_for :plant, url: plant_path(@plant), method: :patch do |f| %>

		<% if @plant && @plant.errors.any? %>
			<div id="error_explanation">
				<h2>
					Existen <%=pluralize(@plant.errors.count, "error", "errores")%> en el formulario.
				</h2>
				<ul class="list-group">
				<ul>
					<% @plant.errors.full_messages.each do |msg| %>
						<li class="list-group-item list-group-item-danger"><%= msg %></li>
					<% end %>
				</ul>	
			</div>
		<% end %>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :name, "Nombre"%> </span>
		<%=f.text_field :name , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :common_name, "Nombres comunes"%></span>
		<%=f.text_area :common_name , :class => "form-control", :rows => "2" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :resume, "Resumen"%></span>
		<%=f.text_area :resume , :class => "form-control", :rows => "2" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :description, "Descripción"%></span>
		<%=f.text_area :description , :class => "form-control", :rows => "4" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :distribution, "Distribución"%></span>
		<%=f.text_field :distribution , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :etnobotanic, "Etnobotánica"%></span>
		<%=f.text_field :etnobotanic , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :latitude, "Latitud"%></span>
		<%=f.text_field :latitude, :maxlenght => "15" , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :longitude, "Longitud"%></span>
		<%=f.text_field :longitude, :maxlenght => "15" , :class => "form-control"%>
	</div>

		<%= f.file_field 'images', multiple: true, :class => "input_imageM" %>

		<div class="imagenes"></div>

		<%=f.submit "Enviar", :class => "btn btn-success", data:{confirm: "¿Esta seguro? En caso de haber imagenes subidas se borrarán."} %>
		
<% end %>


</div>

<a id="volver" href="<%= plants_path %>">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver
</a>

app/views/plants/index.html.erb
<link rel="stylesheet" type="text/css" href="/assets/listas.css">

<div class="superior">
	<a id="volver" href="/">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver al inicio
	</a>
	<% if @user.role != 2 %>
		<a class="btn btn-primary" href="plants/new">Crear nueva planta</a>
	<% end %>
</div>

<div class="container">

	<% if @plants.count == 0 %>
		<h1>No hay plantas creadas</h1>


	<% else %>

    <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Plantas</h3>
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span>Filtrar</button>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="id" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Nombre" disabled></th>

			            <% if @user.role != 2 %>
						<th colspan= 2 >Acciones</th>
						<% end %>

                    </tr>
                </thead>
                <tbody>

			<% @plants.each do |plant| %>
				<tr>
					<td id="num_plant">
						<%= plant.id %>
					</td>
					<td>
						<p><%= link_to plant.name , plant_path(plant) %></p>
					</td>

					<% if @user.role != 2 %>
						<td>
							<%= link_to 'Editar' , edit_plant_path(plant) %>
						</td>
						<td>
							<%= link_to "Eliminar", plant_path(plant), method: :delete, data:{confirm: "¿Esta seguro?"} %>
						</td>
					<% end %>

				</tr>
			<% end %>


                </tbody>
            </table>
        </div>
    </div>

<% end %>

<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/listas.js" ></script>
<% end %>

app/views/plants/new_plant.html.erb
<link rel="stylesheet" type="text/css" href="/assets/newyedit.css">

<a id="volver" href="<%= user_path(@user) %>">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver
</a>

<div class="fold_new ">
<h1>Crear</h1>
<%= form_for :plant, url: plants_path do |f| %>


	<% if @plant && @plant.errors.any? && %>
		<div id="error_explanation">
			<h2>
				Existen <%=pluralize(@plant.errors.count, "error", "errores")%> en el formulario.
			</h2>
			<ul class="list-group">
				<% @plant.errors.full_messages.each do |msg| %>
					<li class="list-group-item list-group-item-danger"><%= msg %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :name, "Nombre"%> </span>
		<%=f.text_field :name , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :common_name, "Nombres comunes"%></span>
		<%=f.text_area :common_name , :class => "form-control", :rows => "2" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :resume, "Resumen"%></span>
		<%=f.text_area :resume , :class => "form-control", :rows => "2" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :description, "Descripción"%></span>
		<%=f.text_area :description , :class => "form-control", :rows => "4" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :distribution, "Distribución"%></span>
		<%=f.text_field :distribution , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :etnobotanic, "Etnobotánica"%></span>
		<%=f.text_field :etnobotanic , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :latitude, "Latitud"%></span>
		<%=f.text_field :latitude, :maxlenght => "15" , :class => "form-control"%>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">
		<%=f.label :longitude, "Longitud"%></span>
		<%=f.text_field :longitude, :maxlenght => "15" , :class => "form-control"%>
	</div>

		<%= f.file_field 'images', multiple: true, :class => "input_imageM" %>

		<div class="imagenes"></div>

		<%=f.submit "Enviar", :class => "btn btn-success" %>
<% end %>


</div>

	<a id="volver" href="<%= plants_path %>">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver
	</a>

<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/imagen_carga.js" ></script>
<% end %>

app/views/plants/show.html.erb
<link rel="stylesheet" type="text/css" href="/assets/showplanta.scss">

<a id="volver" href="<%= root_path %>">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Volver
</a>


<div class="fold_arbol">
	<div class="encabezado">

	<% if @plant.images.length  > 0 %>
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
	    	<!-- Indicators -->
	    	<ol class="carousel-indicators">

	    	<% for i in 0... @plant.images.length %>

		      <% if i == 0 %>
		      	<li data-target="#myCarousel" data-slide-to= '<%= i %>' class="active"></li>
		      <% else %>
		      	<li data-target="#myCarousel" data-slide-to= '<%= i %>' ></li>
			      <% end %>
		    <% end %>

	    	</ol>

	    <!-- Wrapper for slides -->
	    <div class="carousel-inner" role="listbox">

			<% for i in 0... @plant.images.length %>

				<% if i == 0 %>

			      <div class="item active">
			        <img src="<%= @plant.images[i] %>" alt="Chania" width="460" height="345" id="imags">
			      </div>

				<% else %>      

			      <div class="item">
			        <img src="<%= @plant.images[i] %>" alt="Chania" width="460" height="345"id="imags">
			      </div>
		    <% end %>
		<% end %>
		</div>


	    <!-- Left and right controls 
	    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	      <span class="sr-only">Next</span>
	    </a>
		-->

		</div>
	<% else %>
	
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
	    	<!-- Indicators -->
	    	<ol class="carousel-indicators">
		      	<li data-target="#myCarousel" data-slide-to= '0' class="active"></li>
	    	</ol>
    	</div>
		<!-- Wrapper for slides -->
	    <div class="carousel-inner" role="listbox">
	      <div class="item active">
	        <img src="/assets/logo_2.png" alt="Chania" width="460" height="345" id="imags" style="margin:0 auto;">
	      </div>
		</div>

	<% end %>

		<span>
		<h1><%= @plant.name %></h1>
		</span>
	</div>

	<%= form_for :plant, url: addfavs_path(@plant), method: :patch do |f| %>
		<%= f.hidden_field "name" %>
		<%= f.hidden_field "common_name" %>
		<%= f.hidden_field "resume" %>
		<%= f.hidden_field "description" %>
		<%= f.hidden_field "distribution" %>
		<%= f.hidden_field "latitude" %>
		<%= f.hidden_field "longitude" %>

		<% if !@plant.favs.include?(@user.id) %>
			<button type="submit" id="favoritos_btn" style="border:none;">
	  			<span class="glyphicon glyphicon-star-empty" aria-hidden="true">
			</button>		
		<% else %>
			<button type="submit" id="favoritos_btn" style="border:none;">
	  			<span class="glyphicon glyphicon-star" aria-hidden="true">
			</button>	
		<% end %>
	<% end %>
	
	<div class="contenido" >

	<ul>
		<li>
			<div class="alert alert-info" > <%= @plant.common_name %> </div>
		</li>

		<li> <h2>Resumen</h2> </li>
		<li id="cont" > <p> <%= @plant.resume %> </p> </li>

		<li> <h2>Nombre</h2> </li>
		<li> <p> <%= @plant.name %> </li>

		<li> <h2>Descripción</h2> </li>
		<li> <p> <%= @plant.description %> </p> </li>

		<li> <h2>Distribución</h2> </li>
		<li> <p> <%= @plant.distribution %> </p> </li>

		<li> <h2>Etnobotánica</h2> </li>
		<li> <p> <%= @plant.etnobotanic %> </p> </li>
	</ul>

	</div>

<% content_for :javascripts do %>
	<script type="text/javascript" src="/assets/touch.js" ></script>
<% end %>